[project]
name = 'stacks-simple-contracts'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.greeter]
path = 'contracts/greeter.clar'
clarity_version = 3
epoch = 'latest'

[contracts.note-keeper]
path = 'contracts/note-keeper.clar'
clarity_version = 3
epoch = 'latest'

[contracts.simple-counter]
path = 'contracts/simple-counter.clar'
clarity_version = 3
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
